### ISSUE TITLE
Reproducibility of COVID-19 Projections

### ISSUE THREAD

**Issue by daviden1013** [ihmeuw-msca/CurveFit#31]
I tried the authors' example get_started.py under 
https://github.com/ihmeuw-msca/CurveFit/tree/master/example

It's doing simulation, and parameter estimation is as expected. Now to further understand how this model can be fitted with real-world data, I tried to reproduce cumulative USA death count (total death, in the 3rd figure) in https://covid19.healthdata.org/projections

I used numbers from that website, 2/26/2020 to 4/1/2020 each days' total death as training data to project up to August, and the results are different from the website. I also found the unit of time (independent_var) would affect model fitting. I tried "day" and "week" (day/7) and the estimated param are totally different, prediction is also different.
So I am wondering if the authors could share their code and data for projections on https://covid19.healthdata.org/projections

This will help us apply this model with our local county-level and hospital-level data.

**Comment by sbarratt** [comment]
+1. You guys should definitely release it. It would give it much more credibility and maybe there could be more discussion with the public about it. Also would allow govt’s and organizations to play around with parameters.

**Comment by daviden1013** [comment]
Our hospital management team is very interested in this model as the peak is coming and we need some projections about how many beds, ICU and ventilators to prepare. Currently the website only do state-level analysis. If we can understand and reproduce the results, we can fit with our own county and hospital's data.
We really appreciate if the authors could release their raw data and code. I understand the website updates frequently and it's hard to reproduce an output in a specific time point. But if they can provide an input data, a script that process it, and correct parameter estimates (alpha, beta, p), that'll be very helpful.

**Comment by saravkin** [comment]
Please contact **covid19@healthdata.org** to coordinate on new analyses and collaborations! Please see a more detailed explanation here: 
https://github.com/ihmeuw-msca/CurveFit/issues/12#issuecomment-609855004

Meanwhile we will continue with our work, picking up the pace on documentation.

**Comment by adamisntdead** [comment]
Also interested in reproducing the model, I'd like to modify to understand the possible effects of lifting measures before the end of May and it would be hard to do that without first reproducing the original predictions.

**Comment by luistelmocosta** [comment]
> 
> 
> Our hospital management team is very interested in this model as the peak is coming and we need some projections about how many beds, ICU and ventilators to prepare. Currently the website only do state-level analysis. If we can understand and reproduce the results, we can fit with our own county and hospital's data.
> We really appreciate if the authors could release their raw data and code. I understand the website updates frequently and it's hard to reproduce an output in a specific time point. But if they can provide an input data, a script that process it, and correct parameter estimates (alpha, beta, p), that'll be very helpful.

Hey @daviden1013 , same here! Did you get any luck with this project or something similar?

**Comment by benisonp** [comment]
@daviden1013 @luistelmocosta I think we're all in the same boat at the moment! Very interested in getting county-level projections but no idea where to start at the moment.

**Comment by thewanderer41** [comment]
The response we got from using the email was that the UW group is changing the model values daily and that they won't be able to provide a stable version or provide any help.  As I understand it, using just the model code will not help because they are just using the outputs as guide posts and applying additional adjustments manually, meaning that we won't be able to reproduce the values they report.  However, being able to reproduce the output for one day even if it won't match the output they report the next day will at least indicate some level of credibility and provenance in my personal opinion.

I think one of the issues with reproducing the results has been the covariance input.  Coders in the other issue indicated that the values may be a categorical scale of [1, 0.67, 0.34, 0].  However, I think the covariates the model is looking for are weights generated from first fitting the model to the Wuhan data and then applying the resulting covariates to data from other locations.

**Comment by benisonp** [comment]
@thewanderer41 As much as I appreciate their work to begin with, it sounds a little iffy that the additional adjustments are being done manually, unless they release these adjustments for peer review. 

Covariance is definitely something that's been hard for me to understand in terms of what it does just because I haven't been able to find a place where it's been explicitly defined. Your thoughts sound good but I think we need to hear from them definitively in this regard.

**Comment by mbannick** [comment]
Thank you all for your comments and patience in our delayed response. IHME transitioned to using a different modeling approach for COVID-19 forecasting over the last several months so this repository is no longer active. Please see the updated [README](https://github.com/ihmeuw-msca/CurveFit/blob/master/README.md) for more details.
